const API_BASE_URL = window.location.origin.startsWith('http') ? window.location.origin : 'http://localhost:8000';
const SESSION_KEY = 'teluguQaSession';
const HISTORY_KEY = 'aiQuestionHistory';
const $ = (id) => document.getElementById(id);
const authSection = $('authSection');
const workspace = $('workspaceView');
const authForm = $('authForm');
const authSubmitBtn = $('authSubmitBtn');
const authFeedback = $('authFeedback');
const authTabs = $('authTabs');
const accountEmailInput = $('accountEmail');
const emailLabel = $('emailLabel');
const loginTab = $('loginTab');
const createTab = $('createTab');
const passwordInput = $('password');
const usernameInput = $('username');
const recoveryPanel = $('recoveryPanel');
const resetRequestForm = $('resetRequestForm');
const resetRequestBtn = $('resetRequestBtn');
const resetConfirmForm = $('resetConfirmForm');
const resetConfirmBtn = $('resetConfirmBtn');
const apiKeyOutput = $('apiKeyOutput');
const accountBadge = $('accountBadge');
const activeUsername = $('activeUsername');
const sourceTabs = document.querySelectorAll('.source-tab');
const textInput = $('teluguInput');
const inputLanguage = $('inputLang');
const processBtn = $('processBtn');
const resultsSection = $('resultsSection');
const questionResults = $('qaResults');
const errorBox = $('error');
let authMode = 'login';
let questionSet = [];
let practiceMode = false;
let recoveryEmail = '';

window.addEventListener('load', () => {
	restoreSession();
	updateCharacterCount();
	renderHistory();
});

function session() { try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return null; } }
function showAuthenticated(username, apiKey) { authSection.hidden = true; workspace.hidden = false; accountBadge.hidden = false; activeUsername.textContent = username; apiKeyOutput.value = apiKey; }
function restoreSession() { const current = session(); if (current?.apiKey && current?.username) showAuthenticated(current.username, current.apiKey); }
function setAuthMode(mode) { authMode = mode; const create = mode === 'create'; loginTab.classList.toggle('active', !create); createTab.classList.toggle('active', create); accountEmailInput.hidden = !create; emailLabel.hidden = !create; accountEmailInput.required = create; $('authFormOptions').hidden = create; authSubmitBtn.innerHTML = create ? 'Create workspace <span>→</span>' : 'Enter workspace <span>→</span>'; passwordInput.autocomplete = create ? 'new-password' : 'current-password'; authFeedback.hidden = true; }
async function readJson(response) { const type = response.headers.get('content-type') || ''; if (!type.includes('application/json')) throw new Error(`Server returned ${response.status}.`); return response.json(); }
async function submitAuth(event) { event.preventDefault(); hideError(); authFeedback.hidden = true; authSubmitBtn.disabled = true; const account = {username:usernameInput.value.trim(), password:passwordInput.value}; if (authMode === 'create') account.email = accountEmailInput.value.trim(); try { const response = await fetch(`${API_BASE_URL}/${authMode === 'create' ? 'accounts' : 'login'}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(account)}); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || 'Account request failed.'); localStorage.setItem(SESSION_KEY, JSON.stringify({username:data.username, apiKey:data.api_key})); showAuthenticated(data.username, data.api_key); passwordInput.value = ''; } catch (error) { authFeedback.textContent = error.message; authFeedback.hidden = false; } finally { authSubmitBtn.disabled = false; } }
function showRecoveryStep(step) { authTabs.hidden = true; authForm.hidden = true; authFeedback.hidden = true; recoveryPanel.hidden = false; authSection.classList.add('recovery-active'); $('resetRequestView').hidden = step !== 'request'; $('resetSentView').hidden = step !== 'sent'; $('resetConfirmView').hidden = step !== 'confirm'; $('resetCompleteView').hidden = step !== 'complete'; }
function returnToSignIn() { recoveryPanel.hidden = true; authSection.classList.remove('recovery-active'); authTabs.hidden = false; authForm.hidden = false; setAuthMode('login'); $('resetRequestView').hidden = false; $('resetSentView').hidden = true; $('resetConfirmView').hidden = true; $('resetCompleteView').hidden = true; $('recoveryFeedback').hidden = true; resetRequestForm.reset(); resetConfirmForm.reset(); recoveryEmail = ''; }
function startPasswordRecovery() { recoveryEmail = ''; showRecoveryStep('request'); $('requestFeedback').hidden = true; $('recoveryFeedback').hidden = true; }
function maskEmail(email) { const [name, domain] = email.split('@'); return `${name.slice(0, 1)}•••@${domain}`; }
async function submitPasswordResetRequest(event) { event.preventDefault(); $('requestFeedback').hidden = true; resetRequestBtn.disabled = true; resetRequestBtn.innerHTML = 'Sending code…'; try { recoveryEmail = $('resetEmail').value.trim(); const response = await fetch(`${API_BASE_URL}/password-reset/request`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email:recoveryEmail})}); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || 'Could not request a verification code.'); $('resetSentMessage').textContent = `If an account matches ${maskEmail(recoveryEmail)} and email recovery is configured, a verification code will arrive shortly.`; showRecoveryStep('sent'); } catch (error) { const feedback = $('requestFeedback'); feedback.textContent = error.message; feedback.hidden = false; } finally { resetRequestBtn.disabled = false; resetRequestBtn.innerHTML = 'Send verification code <span>→</span>'; } }
async function submitPasswordReset(event) { event.preventDefault(); const feedback = $('recoveryFeedback'); feedback.hidden = true; const newPassword = $('newPassword').value; if (newPassword !== $('confirmPassword').value) { feedback.textContent = 'Those passwords do not match yet.'; feedback.hidden = false; return; } resetConfirmBtn.disabled = true; resetConfirmBtn.innerHTML = 'Updating password…'; try { const response = await fetch(`${API_BASE_URL}/password-reset/confirm`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email:recoveryEmail, otp:$('resetOtp').value.trim(), new_password:newPassword})}); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || 'Could not update your password.'); showRecoveryStep('complete'); } catch (error) { feedback.textContent = error.message; feedback.hidden = false; } finally { resetConfirmBtn.disabled = false; resetConfirmBtn.innerHTML = 'Update password <span>→</span>'; } }
async function extractFile(file) { const current = session(); $('uploadProgress').hidden = false; try { const body = new FormData(); body.append('file', file); const response = await fetch(`${API_BASE_URL}/extract`, {method:'POST', headers:{'X-API-Key':current.apiKey}, body}); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || 'Could not read this file.'); textInput.value = data.text; $('fileStatus').textContent = file.name; updateCharacterCount(); document.querySelector('[data-source="text"]').click(); } catch (error) { showError(error.message); } finally { $('uploadProgress').hidden = true; } }
async function generateQuestions() { const current = session(); const text = textInput.value.trim(); hideError(); clearResults(); if (!current?.apiKey) return showError('Please sign in before generating questions.'); if (text.length < 20) return showError('Add at least 20 characters of study material.'); practiceMode = $('includeAnswers').value === 'false'; processBtn.disabled = true; $('loading').hidden = false; try { const response = await fetch(`${API_BASE_URL}/generate`, {method:'POST', headers:{'Content-Type':'application/json','X-API-Key':current.apiKey}, body:JSON.stringify({text, language:inputLanguage.value, question_count:Number($('questionCount').value), difficulty:$('difficulty').value, question_type:$('questionType').value, include_answers:!practiceMode})}); const data = await readJson(response); if (!response.ok || !data.success) throw new Error(data.detail || data.error || 'No questions were generated.'); questionSet = data.qa_pairs.map((item, index) => ({...item, id:index})); renderQuestions(); saveHistory(); } catch (error) { showError(error.message); } finally { processBtn.disabled = false; $('loading').hidden = true; } }
function renderQuestions() { questionResults.innerHTML = ''; questionSet.forEach((item, index) => { const card = document.createElement('article'); card.className = 'question-card'; const meta = document.createElement('div'); meta.className = 'question-topline'; meta.innerHTML = `<span class="question-number">${String(index + 1).padStart(2,'0')}</span><span class="question-type">${(item.question_type || 'short answer').replace('_',' ')}</span>`; const title = document.createElement('h3'); title.textContent = item.question; card.append(meta, title); if (item.options?.length) { const options = document.createElement('div'); options.className = 'options'; item.options.forEach((option, optionIndex) => { const label = document.createElement('label'); const radio = document.createElement('input'); radio.type = 'radio'; radio.name = `question-${index}`; radio.value = optionIndex; const letter = document.createElement('span'); letter.textContent = String.fromCharCode(65 + optionIndex); const value = document.createElement('b'); value.textContent = option; label.append(radio, letter, value); options.append(label); }); card.append(options); } else if (practiceMode) { const answer = document.createElement('input'); answer.className = 'practice-answer'; answer.placeholder = 'Type your answer…'; answer.dataset.index = index; card.append(answer); } if (!practiceMode) addAnswer(card, item); questionResults.append(card); }); $('resultsMeta').textContent = `${questionSet.length} questions · ${$('difficulty').value} difficulty · ${$('questionType').selectedOptions[0].text}`; $('submitPracticeBtn').hidden = !practiceMode; resultsSection.hidden = false; resultsSection.scrollIntoView({behavior:'smooth'}); }
function addAnswer(card, item) { const block = document.createElement('div'); block.className = 'answer-block'; const label = document.createElement('span'); label.className = 'answer-label'; label.textContent = 'ANSWER'; const value = document.createElement('strong'); value.textContent = item.answer || 'See generated answer'; block.append(label, value); if (item.explanation) { const explanation = document.createElement('p'); explanation.textContent = item.explanation; block.append(explanation); } card.append(block); }
function submitPractice() { let correct = 0; questionSet.forEach((item, index) => { const selected = document.querySelector(`input[name="question-${index}"]:checked`); const typed = document.querySelector(`.practice-answer[data-index="${index}"]`); const answer = selected ? item.options?.[Number(selected.value)] : typed?.value.trim(); if (answer && (String(item.answer || '').toLowerCase().includes(String(answer).toLowerCase()) || String(answer).toLowerCase() === String(item.answer || '').toLowerCase())) correct++; }); const wrong = questionSet.length - correct; $('scorePanel').innerHTML = `<div><strong>${Math.round(correct / questionSet.length * 100)}%</strong><span>Score</span></div><div><strong>${correct}</strong><span>Correct</span></div><div><strong>${wrong}</strong><span>To review</span></div>`; $('scorePanel').hidden = false; document.querySelectorAll('.practice-answer, .options input').forEach(input => input.disabled = true); $('submitPracticeBtn').hidden = true; }
function saveHistory() { const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]'); history.unshift({id:Date.now(), created:new Date().toLocaleString(), count:questionSet.length, questions:questionSet, difficulty:$('difficulty').value}); localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0,12))); renderHistory(); }
function renderHistory() { const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]'); $('historyList').innerHTML = history.length ? history.map(item => `<button class="history-card" data-history="${item.id}"><span class="history-icon">✦</span><span><strong>${item.count} question practice set</strong><small>${item.difficulty} · ${item.created}</small></span><span>→</span></button>`).join('') : '<div class="empty-state">Your generated question papers will appear here.</div>'; $('historyList').querySelectorAll('[data-history]').forEach(button => button.addEventListener('click', () => { const item = history.find(entry => String(entry.id) === button.dataset.history); if (item) { questionSet = item.questions; practiceMode = false; showView('workspace'); renderQuestions(); } })); }
function showView(name) { document.querySelectorAll('.view').forEach(view => view.hidden = view.id !== `${name}View`); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === name)); }
function updateCharacterCount() { $('charCount').textContent = `${textInput.value.length.toLocaleString()} characters`; }
function clearResults() { resultsSection.hidden = true; $('scorePanel').hidden = true; questionResults.innerHTML = ''; }
function hideError() { errorBox.hidden = true; }
function showError(message) { errorBox.textContent = message; errorBox.hidden = false; }

loginTab.addEventListener('click', () => setAuthMode('login')); createTab.addEventListener('click', () => setAuthMode('create')); authForm.addEventListener('submit', submitAuth); $('forgotPasswordBtn').addEventListener('click', startPasswordRecovery); $('backToLoginBtn').addEventListener('click', returnToSignIn); $('resetSentBackBtn').addEventListener('click', returnToSignIn); $('enterOtpBtn').addEventListener('click', () => showRecoveryStep('confirm')); $('resetCompleteBackBtn').addEventListener('click', returnToSignIn); resetRequestForm.addEventListener('submit', submitPasswordResetRequest); resetConfirmForm.addEventListener('submit', submitPasswordReset); processBtn.addEventListener('click', generateQuestions); textInput.addEventListener('input', updateCharacterCount); $('clearTextBtn').addEventListener('click', () => {textInput.value = ''; updateCharacterCount();}); $('contentFile').addEventListener('change', event => event.target.files[0] && extractFile(event.target.files[0])); $('submitPracticeBtn').addEventListener('click', submitPractice); $('anotherBtn').addEventListener('click', clearResults); $('randomizeBtn').addEventListener('click', () => {questionSet.sort(() => Math.random() - .5); renderQuestions();}); $('printBtn').addEventListener('click', () => window.print()); $('logoutBtn').addEventListener('click', () => {localStorage.removeItem(SESSION_KEY); location.reload();});
sourceTabs.forEach(tab => tab.addEventListener('click', () => {sourceTabs.forEach(item => item.classList.toggle('active', item === tab)); $('textSource').hidden = tab.dataset.source !== 'text'; $('uploadSource').hidden = tab.dataset.source !== 'upload';}));
document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => showView(item.dataset.view)));